/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bridgescargo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maske
 */
public class Interface1 extends javax.swing.JFrame {

    public String kullaniciID;
    public String kullaniciSifre;
    public Interface1 interface1;
    public Interface0 interface0;
    public ArrayList<JTextField> txtColmn;
    public ArrayList<JLabel> labelName;
    public ArrayList<String> tblColmnData;
    public ArrayList<String> TemptxtColmnData;
    public boolean emp_button = false;
    public boolean kargoEkleAdmin = false;

    /**
     * Creates new form Interface1
     */
    public Interface1(String sifre, String id) {
        initComponents();
        this.kullaniciID = id;
        this.kullaniciSifre = sifre;
        baslat_tablo(kullaniciID);
        maps.setVisible(false);
        adminKontrol();
        tbltxtandlabelvisibleOnOff(false);
        jTable1.setVisible(false);
        veriekle.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        maps = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        tbltxt1 = new javax.swing.JTextField();
        tbltxt2 = new javax.swing.JTextField();
        tbltxt3 = new javax.swing.JTextField();
        tbltxt4 = new javax.swing.JTextField();
        tbltxt5 = new javax.swing.JTextField();
        tbltxt6 = new javax.swing.JTextField();
        tbltxt7 = new javax.swing.JTextField();
        veriekle = new javax.swing.JButton();
        label8 = new javax.swing.JLabel();
        tbltxt8 = new javax.swing.JTextField();
        label9 = new javax.swing.JLabel();
        tbltxt9 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DeathStrandingGUI7re.jpg"))); // NOI18N

        maps.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        maps.setText("GOOGLE MAPS");
        maps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(maps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maps))
        );

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex , int colIndex){
                return false;
            }
        };
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        label5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label5.setText("Müşteri ID :");

        label6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label6.setText("Teslim Tarihi :");

        label7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label7.setText("Kargo Durum :");

        label1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label1.setText("Kargo ID :");

        label2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label2.setText("Teslim Adresi :");

        label3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label3.setText("Kargo Türü :");

        label4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label4.setText("Müşteri Adı :");

        veriekle.setText("Kargo Onay");
        veriekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veriekleActionPerformed(evt);
            }
        });

        label8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label8.setText("Enlem :");

        label9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label9.setText("Boylam :");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit_1.PNG"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                        .addGap(38, 38, 38)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbltxt1)
                            .addComponent(tbltxt2)
                            .addComponent(tbltxt3)
                            .addComponent(tbltxt4, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(tbltxt8, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 10, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tbltxt5, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addComponent(tbltxt6)
                                        .addComponent(tbltxt7))
                                    .addComponent(tbltxt9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(veriekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbltxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbltxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbltxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbltxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbltxt9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbltxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tbltxt6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbltxt7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbltxt8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(veriekle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("NEW DELIVERY");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("EMPLOYEES");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("TRACK ORDER");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void veriekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veriekleActionPerformed
        int KargoID = Integer.parseInt(tbltxt1.getText());
        String TeslimAdresi = tbltxt2.getText();
        String KargoTuru = tbltxt3.getText();
        String MusteriAdi = tbltxt4.getText();
        String MusteriID = kullaniciID;
        String TeslimTarihi = tbltxt6.getText();
        String KargoDurum = tbltxt7.getText();
        String Enlem = tbltxt8.getText();
        String Boylam = tbltxt9.getText();
        if (kargoEkleAdmin == false) {
            TeslimTarihi = "28/10/2021";
            KargoDurum = "Kargoya Verildi";
            if (KargoID > 0 && TeslimAdresi.length() >= 2 && MusteriAdi.length() >= 2 && MusteriID.length() >= 2 && TeslimTarihi.length() >= 2 && KargoDurum.length() >= 2 && Enlem.length() >= 2 && Boylam.length() >= 2) {
                try {
                    String driver = "com.mysql.cj.jdbc.Driver";
                    String url = "jdbc:mysql://34.135.94.17:3306/BridgesCargo?useSSL=false";
                    String userName = "root";
                    String password = "";
                    Class.forName(driver);

                    Connection myConn = DriverManager.getConnection(url, userName, password);

                    String sorgu = "INSERT INTO " + kullaniciID + " values('" + KargoID + "','" + TeslimAdresi + "','" + KargoTuru + "','" + MusteriAdi + "','" + MusteriID + "','" + TeslimTarihi + "','" + KargoDurum + "','" + Enlem + "','" + Boylam + "')";
                    String sorgu2 = "INSERT INTO delivery values('" + KargoID + "','" + TeslimAdresi + "','" + KargoTuru + "','" + MusteriAdi + "','" + MusteriID + "','" + TeslimTarihi + "','" + KargoDurum + "','" + Enlem + "','" + Boylam + "')";
                    Statement sta = myConn.createStatement();
                    Statement sta2 = myConn.createStatement();

                    int x = sta.executeUpdate(sorgu);
                    int y = sta2.executeUpdate(sorgu2);

                    if (x == 0) {
                        JOptionPane.showMessageDialog(null, "Kargo zaten var !");
                    } else {
                        JOptionPane.showMessageDialog(null, "Kargo basariyla olusturuldu !");
                        jTable1.setModel(new DefaultTableModel());
                        baslat_tablo(kullaniciID);
                        tbltxtress();

                    }

                } catch (Exception e) {

                    if (e.getMessage().indexOf("Duplicate") != -1) {
                        JOptionPane.showMessageDialog(null, "Bu kargo zaten var !");
                    } else {
                        JOptionPane.showMessageDialog(null, "Data Base Hatasi : " + e.getMessage());
                    }

                }
            } else {
                JOptionPane.showMessageDialog(null, "Girilen bilgileri kontrol et !");
            }
        }

        if (kargoEkleAdmin) {
            System.out.println("Girdi");
            try {
                String driver = "com.mysql.cj.jdbc.Driver";
                String url = "jdbc:mysql://34.135.94.17:3306/BridgesCargo?useSSL=false";
                String userName = "root";
                String password = "";
                Class.forName(driver);

                Connection myConn = DriverManager.getConnection(url, userName, password);

                String sorgu = "UPDATE " + MusteriID + " SET teslimtarihi = '" + TeslimTarihi + "',kargodurum = '" + KargoDurum + "' WHERE (kargoid = '" + KargoID + "')";
                String sorgu2 = "UPDATE delivery SET teslimtarihi = '" + TeslimTarihi + "',kargodurum = '" + KargoDurum + "' WHERE (kargoid = '" + KargoID + "')";
                Statement sta = myConn.createStatement();
                Statement sta2 = myConn.createStatement();

                int x = sta.executeUpdate(sorgu);
                int y = sta2.executeUpdate(sorgu2);

                if (x == 0) {
                    JOptionPane.showMessageDialog(null, "Kargo zaten var !");
                } else {
                    JOptionPane.showMessageDialog(null, "Kargo basariyla olusturuldu !");
                    jTable1.setModel(new DefaultTableModel());
                    baslat_tablo("delivery");
                    tbltxtress();

                }
                
             

            } catch (Exception e) {

                if (e.getMessage().indexOf("Duplicate") != -1) {
                    JOptionPane.showMessageDialog(null, "Bu kargo zaten var !");
                } else {
                    JOptionPane.showMessageDialog(null, "Data Base Hatasi : " + e.getMessage());
                }

            }
        }
    }//GEN-LAST:event_veriekleActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        baslat_tablo(kullaniciID);
        emp_button = false;
        tbltxtLockUnlock(false);
        tbltxtandlabelvisibleOnOff(false);
        veriekle.setVisible(false);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        baslat_tablo(kullaniciID);
        emp_button = false;
        tbltxtLockUnlock(true);
        tbltxtandlabelvisibleOnOff(true);
        jTable1.setVisible(true);
        veriekle.setVisible(true);

        label7.setVisible(false);
        tbltxt7.setVisible(false);

        tbltxt5.setText(kullaniciID);
        tbltxt5.setEditable(false);

        tbltxt6.setVisible(false);
        label6.setVisible(false);

        tbltxt6.setText("28/10/2021");
        tbltxt7.setText("Kargoya Verildi");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        baslat_tablo("delivery");

        tbltxtandlabelvisibleOnOff(true);

        jTable1.setVisible(true);
        veriekle.setVisible(true);
        tbltxtLockUnlock(false);
        emp_button = true;

        tbltxt6.setEditable(true);
        tbltxt7.setEditable(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (emp_button) {
            DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
            int colmn_count = jTable1.getColumnCount();
            tblColmnData = new ArrayList<>();

            txtColmn = new ArrayList<>();
            TemptxtColmnData = new ArrayList<>();

            txtColmn.add(tbltxt1);
            txtColmn.add(tbltxt2);
            txtColmn.add(tbltxt3);
            txtColmn.add(tbltxt4);
            txtColmn.add(tbltxt5);
            txtColmn.add(tbltxt6);
            txtColmn.add(tbltxt7);
            txtColmn.add(tbltxt8);
            txtColmn.add(tbltxt9);

            for (int i = 0; i < colmn_count; i++) {
                tblColmnData.add(tblModel.getValueAt(jTable1.getSelectedRow(), i).toString());
            }
            for (int i = 0; i < tblColmnData.size(); i++) {
                txtColmn.get(i).setText(tblColmnData.get(i));

            }

            for (int i = 0; i < txtColmn.size(); i++) {
                TemptxtColmnData.add(txtColmn.get(i).getText());
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void mapsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapsMouseClicked
        googlemap gm = new googlemap();
        gm.setVisible(true);
    }//GEN-LAST:event_mapsMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        interface1.setVisible(false);
        interface0.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    public void al(Interface1 interface1_temp, Interface0 interface0_temp) {
        interface1 = interface1_temp;
        interface0 = interface0_temp;
    }

    public void baslat_tablo(String tabloisim) {
        jTable1.setModel(new DefaultTableModel());

        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();

        ArrayList<String> ColmnName = new ArrayList<>();

        ColmnName.add("KargoID");
        ColmnName.add("TeslimAdresi");
        ColmnName.add("KargoTürü");
        ColmnName.add("MüşteriAdı");
        ColmnName.add("MuşteriID");
        ColmnName.add("Hareket Tarihi");
        ColmnName.add("KargoDurum");
        ColmnName.add("Enlem");
        ColmnName.add("Boylam");

        for (int i = 0; i < ColmnName.size(); i++) {
            tblModel.addColumn(ColmnName.get(i));
        }

        TblTxtandLabelArrayCreate();

        for (int i = 0; i < labelName.size(); i++) {
            labelName.get(i).setText(ColmnName.get(i));
        }
        jTable1.setVisible(true);
        try {
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://34.135.94.17:3306/BridgesCargo?useSSL=false";
            String userName = "root";
            String password = "";
            Class.forName(driver);

            Connection myConn = DriverManager.getConnection(url, userName, password);
            Statement myStat = (Statement) myConn.createStatement();
            ResultSet myRs = myStat.executeQuery("select * from " + tabloisim + "");
            while (myRs.next()) {
                String KargoID = myRs.getString("kargoid");
                String TeslimAdresi = myRs.getString("teslimadresi");
                String KargoTuru = myRs.getString("kargoturu");
                String MusteriAdi = myRs.getString("musteriadi");
                String MusteriID = myRs.getString("musteriid");
                String TeslimTarihi = myRs.getString("teslimtarihi");
                String KargoDurum = myRs.getString("kargodurum");
                String Enlem = myRs.getString("lat");
                String Boylam = myRs.getString("lng");

                String tbData[] = {KargoID, TeslimAdresi, KargoTuru, MusteriAdi, MusteriID, TeslimTarihi, KargoDurum, Enlem, Boylam};

                tblModel.addRow(tbData);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Base Hatasi : " + e.getMessage());
        }

    }

    public void tbltxtandlabelvisibleOnOff(boolean sec) {
        for (int i = 0; i < labelName.size(); i++) {
            if (sec) {
                labelName.get(i).setVisible(true);
                txtColmn.get(i).setVisible(true);
            } else {
                labelName.get(i).setVisible(false);
                txtColmn.get(i).setVisible(false);
            }
        }
    }

    public void TblTxtandLabelArrayCreate() {
        txtColmn = new ArrayList<>();
        labelName = new ArrayList<>();

        txtColmn.add(tbltxt1);
        txtColmn.add(tbltxt2);
        txtColmn.add(tbltxt3);
        txtColmn.add(tbltxt4);
        txtColmn.add(tbltxt5);
        txtColmn.add(tbltxt6);
        txtColmn.add(tbltxt7);
        txtColmn.add(tbltxt8);
        txtColmn.add(tbltxt9);

        labelName.add(label1);
        labelName.add(label2);
        labelName.add(label3);
        labelName.add(label4);
        labelName.add(label5);
        labelName.add(label6);
        labelName.add(label7);
        labelName.add(label8);
        labelName.add(label9);
    }

    public void adminKontrol() {
        if (kullaniciID.equals("admin")) {
            jButton3.setVisible(true);
            jButton2.setVisible(false);
            jButton4.setVisible(false);
            kargoEkleAdmin = true;
            maps.setVisible(true);
        } else {
            jButton3.setVisible(false);
        }
    }

    public void tbltxtress() {
        tbltxt1.setText("");
        tbltxt2.setText("");
        tbltxt3.setText("");
        tbltxt4.setText("");
        //tbltxt5.setText("");
        tbltxt6.setText("");
        tbltxt7.setText("");
        tbltxt8.setText("");
        tbltxt9.setText("");
    }

    public void tbltxtLockUnlock(boolean sec) {
        tbltxt1.setEditable(sec);
        tbltxt2.setEditable(sec);
        tbltxt3.setEditable(sec);
        tbltxt4.setEditable(sec);
        tbltxt5.setEditable(sec);
        tbltxt6.setEditable(sec);
        tbltxt7.setEditable(sec);
        tbltxt8.setEditable(sec);
        tbltxt9.setEditable(sec);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JButton maps;
    private javax.swing.JTextField tbltxt1;
    private javax.swing.JTextField tbltxt2;
    private javax.swing.JTextField tbltxt3;
    private javax.swing.JTextField tbltxt4;
    private javax.swing.JTextField tbltxt5;
    private javax.swing.JTextField tbltxt6;
    private javax.swing.JTextField tbltxt7;
    private javax.swing.JTextField tbltxt8;
    private javax.swing.JTextField tbltxt9;
    private javax.swing.JButton veriekle;
    // End of variables declaration//GEN-END:variables
}
